kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
        streaming-connection-idle-timeout: "0"
  extraPortMappings:
  - containerPort: 30432 # Postgres
    hostPort: 30432
    protocol: TCP
  - containerPort: 30500 # API
    hostPort: 30500
    protocol: TCP
  - containerPort: 30010 # Minio
    hostPort: 2100
    protocol: TCP
