FROM python:3.12-bullseye AS requirements

WORKDIR /app
COPY pyproject.toml poetry.lock /app/
RUN pip install poetry
RUN poetry export > requirements.txt


FROM python:3.12-bullseye

WORKDIR /app
COPY --from=requirements  /app/requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

COPY cross_paths/ /app/cross_paths/

CMD ["uvicorn", "cross_paths:api", "--host", "0.0.0.0", "--port", "5500", "--workers", "2", "--reload"]
