
{{ if ( ne .Values.unittests true ) }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  CROSS_DB_URL: |-
        {{ .Values.db_url | b64enc }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:

      containers:
        - name: api
          image: {{ .Values.registry }}api:{{ .Values.tags.api  }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-secret
          resources:
            requests:
              memory: 2000Mi
              cpu: 600m
            limits:
              memory: 3000Mi
              cpu: 2000m

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: http
      nodePort: 30600
  type: NodePort

{{ end }}
