/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import type { paths } from "../schema";
import type { ServiceOperationQuery, ServiceOperationMutation } from "@openapi-qraft/react";
export interface AuthService {
    /** @summary Request Otp */
    requestOtp: ServiceOperationMutation<{
        method: "post";
        url: "/auth/start-challenge";
        mediaType: "application/json";
    }, NonNullable<paths["/auth/start-challenge"]["post"]["requestBody"]>["content"]["application/json"], paths["/auth/start-challenge"]["post"]["responses"]["200"]["content"]["application/json"], undefined, paths["/auth/start-challenge"]["post"]["responses"]["422"]["content"]["application/json"]>;
    /** @summary Challenge Otp */
    enterOtp: ServiceOperationMutation<{
        method: "post";
        url: "/auth/challenge";
        mediaType: "application/json";
    }, NonNullable<paths["/auth/challenge"]["post"]["requestBody"]>["content"]["application/json"], paths["/auth/challenge"]["post"]["responses"]["200"]["content"]["application/json"], undefined, paths["/auth/challenge"]["post"]["responses"]["422"]["content"]["application/json"]>;
    /** @summary Current User */
    getMe: ServiceOperationQuery<{
        method: "get";
        url: "/auth/me";
    }, paths["/auth/me"]["get"]["responses"]["200"]["content"]["application/json"], undefined, unknown>;
}
export const authService: {
    /** @summary Request Otp */
    requestOtp: {
        schema: {
            method: "post";
            url: "/auth/start-challenge";
            mediaType: "application/json";
        };
    };
    /** @summary Challenge Otp */
    enterOtp: {
        schema: {
            method: "post";
            url: "/auth/challenge";
            mediaType: "application/json";
        };
    };
    /** @summary Current User */
    getMe: {
        schema: {
            method: "get";
            url: "/auth/me";
        };
    };
} = {
    requestOtp: {
        schema: {
            method: "post",
            url: "/auth/start-challenge",
            mediaType: "application/json"
        }
    },
    enterOtp: {
        schema: {
            method: "post",
            url: "/auth/challenge",
            mediaType: "application/json"
        }
    },
    getMe: {
        schema: {
            method: "get",
            url: "/auth/me"
        }
    }
};
