/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import type { paths } from "../schema";
import type { ServiceOperationQuery, ServiceOperationMutation } from "@openapi-qraft/react";
export interface ConversationsService {
    /** @summary Get Conversations */
    getAllConversations: ServiceOperationQuery<{
        method: "get";
        url: "/conversations/";
    }, paths["/conversations/"]["get"]["responses"]["200"]["content"]["application/json"], undefined, unknown>;
    /** @summary Create Conversation */
    createConversation: ServiceOperationMutation<{
        method: "post";
        url: "/conversations/";
        mediaType: "application/json";
    }, NonNullable<paths["/conversations/"]["post"]["requestBody"]>["content"]["application/json"], paths["/conversations/"]["post"]["responses"]["201"]["content"]["application/json"], undefined, paths["/conversations/"]["post"]["responses"]["422"]["content"]["application/json"]>;
    /** @summary Get Conversation */
    getConversation: ServiceOperationQuery<{
        method: "get";
        url: "/conversations/{conversation_id}";
    }, paths["/conversations/{conversation_id}"]["get"]["responses"]["200"]["content"]["application/json"], paths["/conversations/{conversation_id}"]["get"]["parameters"], paths["/conversations/{conversation_id}"]["get"]["responses"]["422"]["content"]["application/json"]>;
    /** @summary Create Message */
    createMessage: ServiceOperationMutation<{
        method: "post";
        url: "/conversations/{conversation_id}/messages";
        mediaType: "application/json";
    }, NonNullable<paths["/conversations/{conversation_id}/messages"]["post"]["requestBody"]>["content"]["application/json"], paths["/conversations/{conversation_id}/messages"]["post"]["responses"]["201"]["content"]["application/json"], paths["/conversations/{conversation_id}/messages"]["post"]["parameters"], paths["/conversations/{conversation_id}/messages"]["post"]["responses"]["422"]["content"]["application/json"]>;
    /** @summary Seed Dummy Data */
    seedConversations: ServiceOperationMutation<{
        method: "post";
        url: "/conversations/seed";
    }, undefined, paths["/conversations/seed"]["post"]["responses"]["201"]["content"]["application/json"], undefined, unknown>;
}
export const conversationsService: {
    /** @summary Get Conversations */
    getAllConversations: {
        schema: {
            method: "get";
            url: "/conversations/";
        };
    };
    /** @summary Create Conversation */
    createConversation: {
        schema: {
            method: "post";
            url: "/conversations/";
            mediaType: "application/json";
        };
    };
    /** @summary Get Conversation */
    getConversation: {
        schema: {
            method: "get";
            url: "/conversations/{conversation_id}";
        };
    };
    /** @summary Create Message */
    createMessage: {
        schema: {
            method: "post";
            url: "/conversations/{conversation_id}/messages";
            mediaType: "application/json";
        };
    };
    /** @summary Seed Dummy Data */
    seedConversations: {
        schema: {
            method: "post";
            url: "/conversations/seed";
        };
    };
} = {
    getAllConversations: {
        schema: {
            method: "get",
            url: "/conversations/"
        }
    },
    createConversation: {
        schema: {
            method: "post",
            url: "/conversations/",
            mediaType: "application/json"
        }
    },
    getConversation: {
        schema: {
            method: "get",
            url: "/conversations/{conversation_id}"
        }
    },
    createMessage: {
        schema: {
            method: "post",
            url: "/conversations/{conversation_id}/messages",
            mediaType: "application/json"
        }
    },
    seedConversations: {
        schema: {
            method: "post",
            url: "/conversations/seed"
        }
    }
};
