/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import type { paths } from "../schema";
import type { ServiceOperationQuery, ServiceOperationMutation } from "@openapi-qraft/react";
export interface ConversationsService {
    /** @summary Get Conversations */
    getAllConversations: ServiceOperationQuery<{
        method: "get";
        url: "/conversations/";
    }, paths["/conversations/"]["get"]["responses"]["200"]["content"]["application/json"], undefined, unknown>;
    /** @summary Get Messages */
    getMessagesInConversation: ServiceOperationQuery<{
        method: "get";
        url: "/conversations/{conversation_id}";
    }, paths["/conversations/{conversation_id}"]["get"]["responses"]["200"]["content"]["application/json"], paths["/conversations/{conversation_id}"]["get"]["parameters"], paths["/conversations/{conversation_id}"]["get"]["responses"]["422"]["content"]["application/json"]>;
    /** @summary Seed Dummy Data */
    seedConversations: ServiceOperationMutation<{
        method: "post";
        url: "/conversations/seed";
    }, undefined, paths["/conversations/seed"]["post"]["responses"]["201"]["content"]["application/json"], undefined, unknown>;
}
export const conversationsService: {
    /** @summary Get Conversations */
    getAllConversations: {
        schema: {
            method: "get";
            url: "/conversations/";
        };
    };
    /** @summary Get Messages */
    getMessagesInConversation: {
        schema: {
            method: "get";
            url: "/conversations/{conversation_id}";
        };
    };
    /** @summary Seed Dummy Data */
    seedConversations: {
        schema: {
            method: "post";
            url: "/conversations/seed";
        };
    };
} = {
    getAllConversations: {
        schema: {
            method: "get",
            url: "/conversations/"
        }
    },
    getMessagesInConversation: {
        schema: {
            method: "get",
            url: "/conversations/{conversation_id}"
        }
    },
    seedConversations: {
        schema: {
            method: "post",
            url: "/conversations/seed"
        }
    }
};
