/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import type { paths } from "../schema";
import type { ServiceOperationQuery } from "@openapi-qraft/react";
export interface ConversationService {
    /** @summary Get Conversations */
    listConversations: ServiceOperationQuery<{
        method: "get";
        url: "/conversation/tags";
    }, paths["/conversation/tags"]["get"]["responses"]["200"]["content"]["application/json"], undefined, unknown>;
}
export const conversationService: {
    /** @summary Get Conversations */
    listConversations: {
        schema: {
            method: "get";
            url: "/conversation/tags";
        };
    };
} = {
    listConversations: {
        schema: {
            method: "get",
            url: "/conversation/tags"
        }
    }
};
