/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import type { paths } from "../schema";
import type { ServiceOperationQuery } from "@openapi-qraft/react";
export interface HelloService {
    /** @summary Hello World */
    helloWorldHelloGet: ServiceOperationQuery<{
        method: "get";
        url: "/hello";
    }, paths["/hello"]["get"]["responses"]["200"]["content"]["application/json"], undefined, unknown>;
}
export const helloService: {
    /** @summary Hello World */
    helloWorldHelloGet: {
        schema: {
            method: "get";
            url: "/hello";
        };
    };
} = {
    helloWorldHelloGet: {
        schema: {
            method: "get",
            url: "/hello"
        }
    }
};
