/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import { OpportunitiesService, opportunitiesService } from "./OpportunitiesService";
import { DatabaseService, databaseService } from "./DatabaseService";
import { OrganizationsService, organizationsService } from "./OrganizationsService";
import { AuthService, authService } from "./AuthService";
import { ConversationsService, conversationsService } from "./ConversationsService";
import { UsersService, usersService } from "./UsersService";
import { HelloService, helloService } from "./HelloService";
import { ProtectedService, protectedService } from "./ProtectedService";
export type Services = {
    opportunities: OpportunitiesService;
    database: DatabaseService;
    organizations: OrganizationsService;
    auth: AuthService;
    conversations: ConversationsService;
    users: UsersService;
    hello: HelloService;
    protected: ProtectedService;
};
export const services = {
    opportunities: opportunitiesService,
    database: databaseService,
    organizations: organizationsService,
    auth: authService,
    conversations: conversationsService,
    users: usersService,
    hello: helloService,
    protected: protectedService
} as const;
