/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import { OpportunitiesService, opportunitiesService } from "./OpportunitiesService";
import { DatabaseService, databaseService } from "./DatabaseService";
import { OrganizationsService, organizationsService } from "./OrganizationsService";
import { AuthService, authService } from "./AuthService";
import { ConversationService, conversationService } from "./ConversationService";
import { MessagesService, messagesService } from "./MessagesService";
import { HelloService, helloService } from "./HelloService";
import { ProtectedService, protectedService } from "./ProtectedService";
export type Services = {
    opportunities: OpportunitiesService;
    database: DatabaseService;
    organizations: OrganizationsService;
    auth: AuthService;
    conversation: ConversationService;
    messages: MessagesService;
    hello: HelloService;
    protected: ProtectedService;
};
export const services = {
    opportunities: opportunitiesService,
    database: databaseService,
    organizations: organizationsService,
    auth: authService,
    conversation: conversationService,
    messages: messagesService,
    hello: helloService,
    protected: protectedService
} as const;
