/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import { OpportunitiesService, opportunitiesService } from "./OpportunitiesService";
import { DatabaseService, databaseService } from "./DatabaseService";
import { OrganizationsService, organizationsService } from "./OrganizationsService";
import { HelloService, helloService } from "./HelloService";
export type Services = {
    opportunities: OpportunitiesService;
    database: DatabaseService;
    organizations: OrganizationsService;
    hello: HelloService;
};
export const services = {
    opportunities: opportunitiesService,
    database: databaseService,
    organizations: organizationsService,
    hello: helloService
} as const;
