/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import type { paths } from "../schema";
import type { ServiceOperationQuery } from "@openapi-qraft/react";
export interface MessagesService {
    /** @summary Get Conversations */
    listMessages: ServiceOperationQuery<{
        method: "get";
        url: "/messages/tags";
    }, paths["/messages/tags"]["get"]["responses"]["200"]["content"]["application/json"], undefined, unknown>;
}
export const messagesService: {
    /** @summary Get Conversations */
    listMessages: {
        schema: {
            method: "get";
            url: "/messages/tags";
        };
    };
} = {
    listMessages: {
        schema: {
            method: "get",
            url: "/messages/tags"
        }
    }
};
