/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import type { paths } from "../schema";
import type { ServiceOperationQuery } from "@openapi-qraft/react";
export interface MessagesService {
    /** @summary Get Messages */
    getMessagesmessagesGet: ServiceOperationQuery<{
        method: "get";
        url: "messages";
    }, paths["messages"]["get"]["responses"]["200"]["content"]["application/json"], undefined, unknown>;
}
export const messagesService: {
    /** @summary Get Messages */
    getMessagesmessagesGet: {
        schema: {
            method: "get";
            url: "messages";
        };
    };
} = {
    getMessagesmessagesGet: {
        schema: {
            method: "get",
            url: "messages"
        }
    }
};
