/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import type { paths } from "../schema";
import type { AreAllOptional, InvalidateQueryFilters, MutationFiltersByMutationKey, MutationFiltersByParameters, MutationVariables, OperationInfiniteData, PartialParameters, QueryFiltersByParameters, QueryFiltersByQueryKey, QueryFnOptionsByParameters, QueryFnOptionsByQueryKey, RequestFnResponse, ServiceOperationEnsureInfiniteQueryDataOptions, ServiceOperationEnsureQueryDataOptions, ServiceOperationFetchInfiniteQueryOptions, ServiceOperationFetchQueryOptions, ServiceOperationInfiniteQueryKey, ServiceOperationMutationFnOptions, ServiceOperationMutationKey, ServiceOperationQueryKey, ServiceOperationUseMutationOptions, UseQueryOptionsForUseQueries, UseQueryOptionsForUseSuspenseQuery, WithOptional } from "@openapi-qraft/tanstack-query-react-types";
import type { CancelOptions, InfiniteQueryPageParamsOptions, InvalidateOptions, Mutation, MutationState, NoInfer, QueryState, RefetchOptions, ResetOptions, SetDataOptions, Updater } from "@tanstack/query-core";
import type { DefinedInitialDataInfiniteOptions, DefinedInitialDataOptions, DefinedUseInfiniteQueryResult, DefinedUseQueryResult, UndefinedInitialDataInfiniteOptions, UndefinedInitialDataOptions, UseInfiniteQueryResult, UseMutationResult, UseQueryResult, UseSuspenseInfiniteQueryOptions, UseSuspenseInfiniteQueryResult, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
export interface OpportunitiesService {
    /** @summary Get Opportunities */
    listOpportunities: {
        /** @summary Get Opportunities */
        cancelQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<ListOpportunitiesSchema, ListOpportunitiesData, TInfinite, ListOpportunitiesParameters, ListOpportunitiesError> | QueryFiltersByQueryKey<ListOpportunitiesSchema, ListOpportunitiesData, TInfinite, ListOpportunitiesParameters, ListOpportunitiesError>, options?: CancelOptions): Promise<void>;
        /** @summary Get Opportunities */
        getQueryKey(parameters: ListOpportunitiesParameters | void): ServiceOperationQueryKey<ListOpportunitiesSchema, ListOpportunitiesParameters>;
        /**
         * Performs asynchronous data fetching, manages loading states and error handling.
         *
         * @summary Get Opportunities
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQuery|`useQuery(...)` documentation}
         * @example Query without parameters
         * ```ts
         * const { data, isLoading } = qraft.opportunitiesService.listOpportunities.useQuery()
         * ```
         */
        useQuery<TData = ListOpportunitiesData>(parameters: ServiceOperationQueryKey<ListOpportunitiesSchema, ListOpportunitiesParameters> | (ListOpportunitiesParameters | void), options?: Omit<UndefinedInitialDataOptions<ListOpportunitiesData, ListOpportunitiesError, TData, ServiceOperationQueryKey<ListOpportunitiesSchema, ListOpportunitiesParameters>>, "queryKey">): UseQueryResult<TData, ListOpportunitiesError | Error>;
        /**
         * Performs asynchronous data fetching, manages loading states and error handling.
         *
         * @summary Get Opportunities
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQuery|`useQuery(...)` documentation}
         * @example Query without parameters
         * ```ts
         * const { data, isLoading } = qraft.opportunitiesService.listOpportunities.useQuery()
         * ```
         */
        useQuery<TData = ListOpportunitiesData>(parameters: ServiceOperationQueryKey<ListOpportunitiesSchema, ListOpportunitiesParameters> | (ListOpportunitiesParameters | void), options: Omit<DefinedInitialDataOptions<ListOpportunitiesData, ListOpportunitiesError, TData, ServiceOperationQueryKey<ListOpportunitiesSchema, ListOpportunitiesParameters>>, "queryKey">): DefinedUseQueryResult<TData, ListOpportunitiesError | Error>;
        /** @summary Get Opportunities */
        fetchInfiniteQuery<TPageParam extends ListOpportunitiesParameters>(options: ServiceOperationFetchInfiniteQueryOptions<ListOpportunitiesSchema, ListOpportunitiesData, ListOpportunitiesParameters, TPageParam, ListOpportunitiesError>): Promise<OperationInfiniteData<ListOpportunitiesData, ListOpportunitiesParameters>>;
        /** @summary Get Opportunities */
        prefetchInfiniteQuery<TPageParam extends ListOpportunitiesParameters>(options: ServiceOperationFetchInfiniteQueryOptions<ListOpportunitiesSchema, ListOpportunitiesData, ListOpportunitiesParameters, TPageParam, ListOpportunitiesError>): Promise<void>;
        /** @summary Get Opportunities */
        ensureInfiniteQueryData<TPageParam extends ListOpportunitiesParameters>(options: ServiceOperationEnsureInfiniteQueryDataOptions<ListOpportunitiesSchema, ListOpportunitiesData, ListOpportunitiesParameters, TPageParam, ListOpportunitiesError>): Promise<OperationInfiniteData<ListOpportunitiesData, ListOpportunitiesParameters>>;
        /** @summary Get Opportunities */
        fetchQuery(options: ServiceOperationFetchQueryOptions<ListOpportunitiesSchema, ListOpportunitiesData, ListOpportunitiesParameters, ListOpportunitiesError> | void): Promise<ListOpportunitiesData>;
        /** @summary Get Opportunities */
        prefetchQuery(options: ServiceOperationFetchQueryOptions<ListOpportunitiesSchema, ListOpportunitiesData, ListOpportunitiesParameters, ListOpportunitiesError> | void): Promise<void>;
        /** @summary Get Opportunities */
        ensureQueryData(options: ServiceOperationEnsureQueryDataOptions<ListOpportunitiesSchema, ListOpportunitiesData, ListOpportunitiesParameters, ListOpportunitiesError> | void): Promise<ListOpportunitiesData>;
        /** @summary Get Opportunities */
        getInfiniteQueryData(parameters: ServiceOperationInfiniteQueryKey<ListOpportunitiesSchema, ListOpportunitiesParameters> | (ListOpportunitiesParameters | void)): OperationInfiniteData<ListOpportunitiesData, ListOpportunitiesParameters> | undefined;
        /** @summary Get Opportunities */
        getQueriesData<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<ListOpportunitiesSchema, ListOpportunitiesData, TInfinite, ListOpportunitiesParameters, ListOpportunitiesError> | QueryFiltersByQueryKey<ListOpportunitiesSchema, ListOpportunitiesData, TInfinite, ListOpportunitiesParameters, ListOpportunitiesError>): TInfinite extends true ? Array<[
            queryKey: ServiceOperationInfiniteQueryKey<ListOpportunitiesSchema, ListOpportunitiesParameters>,
            data: NoInfer<OperationInfiniteData<ListOpportunitiesData, ListOpportunitiesParameters>> | undefined
        ]> : Array<[
            queryKey: ServiceOperationQueryKey<ListOpportunitiesSchema, ListOpportunitiesParameters>,
            data: ListOpportunitiesData | undefined
        ]>;
        /** @summary Get Opportunities */
        getQueryData(parameters: ServiceOperationQueryKey<ListOpportunitiesSchema, ListOpportunitiesParameters> | (ListOpportunitiesParameters | void)): ListOpportunitiesData | undefined;
        /** @summary Get Opportunities */
        getQueryState(parameters: ServiceOperationQueryKey<ListOpportunitiesSchema, ListOpportunitiesParameters> | (ListOpportunitiesParameters | void)): QueryState<ListOpportunitiesData, ListOpportunitiesError> | undefined;
        /** @summary Get Opportunities */
        getInfiniteQueryState(parameters: ListOpportunitiesParameters | ServiceOperationInfiniteQueryKey<ListOpportunitiesSchema, ListOpportunitiesParameters> | void): QueryState<OperationInfiniteData<ListOpportunitiesData, ListOpportunitiesParameters>, ListOpportunitiesError> | undefined;
        /** @summary Get Opportunities */
        invalidateQueries<TInfinite extends boolean = false>(filters?: InvalidateQueryFilters<ListOpportunitiesSchema, ListOpportunitiesData, TInfinite, ListOpportunitiesParameters, ListOpportunitiesError>, options?: InvalidateOptions): Promise<void>;
        /** @summary Get Opportunities */
        isFetching<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<ListOpportunitiesSchema, ListOpportunitiesData, TInfinite, ListOpportunitiesParameters, ListOpportunitiesError> | QueryFiltersByQueryKey<ListOpportunitiesSchema, ListOpportunitiesData, TInfinite, ListOpportunitiesParameters, ListOpportunitiesError>): number;
        /** @summary Get Opportunities */
        <TMeta extends Record<string, any>, TSignal extends AbortSignal = AbortSignal>(options: QueryFnOptionsByQueryKey<ListOpportunitiesSchema, ListOpportunitiesParameters, TMeta, TSignal> | (QueryFnOptionsByParameters<ListOpportunitiesParameters, TMeta, TSignal> | void), client?: (schema: ListOpportunitiesSchema, options: {
            parameters: ListOpportunitiesParameters;
            signal?: TSignal;
            meta?: TMeta;
        }) => Promise<RequestFnResponse<ListOpportunitiesData, ListOpportunitiesError>>): Promise<RequestFnResponse<ListOpportunitiesData, ListOpportunitiesError>>;
        /** @summary Get Opportunities */
        refetchQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<ListOpportunitiesSchema, ListOpportunitiesData, TInfinite, ListOpportunitiesParameters, ListOpportunitiesError> | QueryFiltersByQueryKey<ListOpportunitiesSchema, ListOpportunitiesData, TInfinite, ListOpportunitiesParameters, ListOpportunitiesError>, options?: RefetchOptions): Promise<void>;
        /** @summary Get Opportunities */
        removeQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<ListOpportunitiesSchema, ListOpportunitiesData, TInfinite, ListOpportunitiesParameters, ListOpportunitiesError> | QueryFiltersByQueryKey<ListOpportunitiesSchema, ListOpportunitiesData, TInfinite, ListOpportunitiesParameters, ListOpportunitiesError>): void;
        /** @summary Get Opportunities */
        resetQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<ListOpportunitiesSchema, ListOpportunitiesData, TInfinite, ListOpportunitiesParameters, ListOpportunitiesError> | QueryFiltersByQueryKey<ListOpportunitiesSchema, ListOpportunitiesData, TInfinite, ListOpportunitiesParameters, ListOpportunitiesError>, options?: ResetOptions): Promise<void>;
        /** @summary Get Opportunities */
        setInfiniteQueryData(parameters: ListOpportunitiesParameters | ServiceOperationInfiniteQueryKey<ListOpportunitiesSchema, ListOpportunitiesParameters>, updater: Updater<NoInfer<OperationInfiniteData<ListOpportunitiesData, ListOpportunitiesParameters>> | undefined, NoInfer<OperationInfiniteData<ListOpportunitiesData, ListOpportunitiesParameters>> | undefined>, options?: SetDataOptions): OperationInfiniteData<ListOpportunitiesData, ListOpportunitiesParameters> | undefined;
        /** @summary Get Opportunities */
        setQueriesData<TInfinite extends boolean = false>(filters: QueryFiltersByParameters<ListOpportunitiesSchema, ListOpportunitiesData, TInfinite, ListOpportunitiesParameters, ListOpportunitiesError> | QueryFiltersByQueryKey<ListOpportunitiesSchema, ListOpportunitiesData, TInfinite, ListOpportunitiesParameters, ListOpportunitiesError>, updater: Updater<NoInfer<ListOpportunitiesData> | undefined, NoInfer<ListOpportunitiesData> | undefined>, options?: SetDataOptions): Array<ListOpportunitiesData | undefined>;
        /** @summary Get Opportunities */
        setQueryData(parameters: (ListOpportunitiesParameters | undefined) | ServiceOperationQueryKey<ListOpportunitiesSchema, ListOpportunitiesParameters>, updater: Updater<NoInfer<ListOpportunitiesData> | undefined, NoInfer<ListOpportunitiesData> | undefined>, options?: SetDataOptions): ListOpportunitiesData | undefined;
        /** @summary Get Opportunities */
        getInfiniteQueryKey(parameters: ListOpportunitiesParameters | void): ServiceOperationInfiniteQueryKey<ListOpportunitiesSchema, ListOpportunitiesParameters>;
        /**
         * Performs asynchronous data fetching with support for infinite scrolling scenarios.
         * Manages paginated data and provides utilities for fetching additional pages.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useInfiniteQuery|`useInfiniteQuery(...)` documentation}
         *
         * @example Infinite Query
         * ```ts
         * const { data, isLoading, fetchNextPage } = qraft.opportunitiesService.listOpportunities.useInfiniteQuery({}, {
         *     initialPageParam: {},
         *     getNextPageParam: (lastPage, allPages, lastPageParam, allPageParams) => getNextPageParams(lastPage)
         * })
         *
         * console.log(data);
         * fetchNextPage(); // Fetch the next page
         * ```
         */
        useInfiniteQuery<TPageParam extends ListOpportunitiesParameters, TQueryFnData = ListOpportunitiesData, TData = OperationInfiniteData<TQueryFnData, ListOpportunitiesParameters>>(parameters: ServiceOperationInfiniteQueryKey<ListOpportunitiesSchema, ListOpportunitiesParameters> | (ListOpportunitiesParameters | void), options: Omit<UndefinedInitialDataInfiniteOptions<TQueryFnData, ListOpportunitiesError, TData, ServiceOperationInfiniteQueryKey<ListOpportunitiesSchema, ListOpportunitiesParameters>, PartialParameters<TPageParam>>, "queryKey" | "getPreviousPageParam" | "getNextPageParam" | "initialPageParam"> & InfiniteQueryPageParamsOptions<TQueryFnData, PartialParameters<TPageParam>>): UseInfiniteQueryResult<TData, ListOpportunitiesError | Error>;
        /**
         * Performs asynchronous data fetching with support for infinite scrolling scenarios.
         * Manages paginated data and provides utilities for fetching additional pages.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useInfiniteQuery|`useInfiniteQuery(...)` documentation}
         *
         * @example Infinite Query
         * ```ts
         * const { data, isLoading, fetchNextPage } = qraft.opportunitiesService.listOpportunities.useInfiniteQuery({}, {
         *     initialPageParam: {},
         *     getNextPageParam: (lastPage, allPages, lastPageParam, allPageParams) => getNextPageParams(lastPage)
         * })
         *
         * console.log(data);
         * fetchNextPage(); // Fetch the next page
         * ```
         */
        useInfiniteQuery<TPageParam extends ListOpportunitiesParameters, TQueryFnData = ListOpportunitiesData, TData = OperationInfiniteData<TQueryFnData, ListOpportunitiesParameters>>(parameters: ServiceOperationInfiniteQueryKey<ListOpportunitiesSchema, ListOpportunitiesParameters> | (ListOpportunitiesParameters | void), options: Omit<DefinedInitialDataInfiniteOptions<TQueryFnData, ListOpportunitiesError, TData, ServiceOperationInfiniteQueryKey<ListOpportunitiesSchema, ListOpportunitiesParameters>, PartialParameters<TPageParam>>, "queryKey" | "getPreviousPageParam" | "getNextPageParam" | "initialPageParam"> & InfiniteQueryPageParamsOptions<ListOpportunitiesData, PartialParameters<TPageParam>>): DefinedUseInfiniteQueryResult<TData, ListOpportunitiesError | Error>;
        /**
         * Monitors the number of queries currently fetching, matching the provided filters.
         * Useful for creating loading indicators or performing actions based on active requests.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useIsFetching|`useIsFetching(...)` documentation}
         * @example Checks the total number of queries fetching from the specified service method,
         * both normal and infinite. If no parameters are provided, no filtering is applied.
         * ```ts
         * const listOpportunitiesTotal = qraft.opportunitiesService.listOpportunities.useIsFetching()
         * ```
         */
        useIsFetching<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<ListOpportunitiesSchema, ListOpportunitiesData, TInfinite, ListOpportunitiesParameters, ListOpportunitiesError> | QueryFiltersByQueryKey<ListOpportunitiesSchema, ListOpportunitiesData, TInfinite, ListOpportunitiesParameters, ListOpportunitiesError>): number;
        /**
         * Allows you to execute multiple asynchronous data fetching operations concurrently. This is especially useful for managing complex data dependencies in parallel.
         *
         * @summary Get Opportunities
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQueries|`useQueries(...)` documentation}
         * @example Multiple queries. Returns `data`, `error`, `isSuccess` and other properties.
         * ```ts
         * const listOpportunitiesResults = qraft.opportunitiesService.listOpportunities.useQueries({
         *     queries: [
         *         {},
         *         {}
         *     ]
         * });
         * listOpportunitiesResults.forEach(({ isSuccess, data, error }) => console.log({ isSuccess, data, error }));
         * ```
         * @example Combined results. Only the data will be returned.
         * ```ts
         * const listOpportunitiesCombinedResults = qraft.opportunitiesService.listOpportunities.useQueries({
         *     combine: results => results.map(result => result.data),
         *     queries: [
         *         {},
         *         {}
         *     ]
         * });
         * listOpportunitiesCombinedResults.forEach(data => console.log({ data }));
         * ```
         */
        useQueries<T extends Array<UseQueryOptionsForUseQueries<ListOpportunitiesSchema, ListOpportunitiesParameters, ListOpportunitiesData, ListOpportunitiesError>>, TCombinedResult = Array<UseQueryResult<ListOpportunitiesData, ListOpportunitiesError>>>(options: {
            queries: T;
            combine?: (results: Array<UseQueryResult<ListOpportunitiesData, ListOpportunitiesError>>) => TCombinedResult;
        }): TCombinedResult;
        /** @summary Get Opportunities */
        getQueryKey(parameters: ListOpportunitiesParameters | void): ServiceOperationQueryKey<ListOpportunitiesSchema, ListOpportunitiesParameters>;
        /**
         * Performs asynchronous data fetching, manages loading states and error handling.
         *
         * @summary Get Opportunities
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQuery|`useQuery(...)` documentation}
         * @example Query without parameters
         * ```ts
         * const { data, isLoading } = qraft.opportunitiesService.listOpportunities.useQuery()
         * ```
         */
        useQuery<TData = ListOpportunitiesData>(parameters: ServiceOperationQueryKey<ListOpportunitiesSchema, ListOpportunitiesParameters> | (ListOpportunitiesParameters | void), options?: Omit<UndefinedInitialDataOptions<ListOpportunitiesData, ListOpportunitiesError, TData, ServiceOperationQueryKey<ListOpportunitiesSchema, ListOpportunitiesParameters>>, "queryKey">): UseQueryResult<TData, ListOpportunitiesError | Error>;
        /**
         * Performs asynchronous data fetching, manages loading states and error handling.
         *
         * @summary Get Opportunities
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQuery|`useQuery(...)` documentation}
         * @example Query without parameters
         * ```ts
         * const { data, isLoading } = qraft.opportunitiesService.listOpportunities.useQuery()
         * ```
         */
        useQuery<TData = ListOpportunitiesData>(parameters: ServiceOperationQueryKey<ListOpportunitiesSchema, ListOpportunitiesParameters> | (ListOpportunitiesParameters | void), options: Omit<DefinedInitialDataOptions<ListOpportunitiesData, ListOpportunitiesError, TData, ServiceOperationQueryKey<ListOpportunitiesSchema, ListOpportunitiesParameters>>, "queryKey">): DefinedUseQueryResult<TData, ListOpportunitiesError | Error>;
        /**
         * Performs asynchronous data fetching with support for infinite scrolling scenarios.
         * Manages paginated data and provides utilities for fetching additional pages.
         * It functions similarly to `useInfiniteQuery`, but with added support for React Suspense.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useSuspenseInfiniteQuery|`useSuspenseInfiniteQuery(...)` documentation}
         *
         * @example Suspense Infinite Query
         * ```ts
         * const { data, isLoading, fetchNextPage } = qraft.opportunitiesService.listOpportunities.useSuspenseInfiniteQuery({}, {
         *     initialPageParam: {},
         *     getNextPageParam: (lastPage, allPages, lastPageParam, allPageParams) => getNextPageParams(lastPage)
         * })
         *
         * console.log(data);
         * fetchNextPage(); // Fetch the next page
         * ```
         */
        useSuspenseInfiniteQuery<TPageParam extends ListOpportunitiesParameters, TData = ListOpportunitiesData>(parameters: ServiceOperationInfiniteQueryKey<ListOpportunitiesSchema, ListOpportunitiesParameters> | (ListOpportunitiesParameters | void), options: Omit<UseSuspenseInfiniteQueryOptions<ListOpportunitiesData, ListOpportunitiesError, OperationInfiniteData<TData, ListOpportunitiesParameters>, ListOpportunitiesData, ServiceOperationInfiniteQueryKey<ListOpportunitiesSchema, ListOpportunitiesParameters>, PartialParameters<TPageParam>>, "queryKey" | "getPreviousPageParam" | "getNextPageParam" | "initialPageParam"> & InfiniteQueryPageParamsOptions<ListOpportunitiesData, PartialParameters<TPageParam>>): UseSuspenseInfiniteQueryResult<OperationInfiniteData<TData, ListOpportunitiesParameters>, ListOpportunitiesError | Error>;
        /** @summary Get Opportunities */
        useSuspenseQueries<T extends Array<UseQueryOptionsForUseSuspenseQuery<ListOpportunitiesSchema, ListOpportunitiesParameters, ListOpportunitiesData, ListOpportunitiesError>>, TCombinedResult = Array<UseSuspenseQueryResult<ListOpportunitiesData, ListOpportunitiesError>>>(options: {
            queries: T;
            combine?: (results: Array<WithOptional<UseSuspenseQueryResult<ListOpportunitiesData, ListOpportunitiesError>, "data">>) => TCombinedResult;
        }): TCombinedResult;
        /** @summary Get Opportunities */
        useSuspenseQuery<TData = ListOpportunitiesData>(parameters: ServiceOperationQueryKey<ListOpportunitiesSchema, ListOpportunitiesParameters> | (ListOpportunitiesParameters | void), options?: Omit<UseSuspenseQueryOptions<ListOpportunitiesData, ListOpportunitiesError, TData, ServiceOperationQueryKey<ListOpportunitiesSchema, ListOpportunitiesParameters>>, "queryKey">): UseSuspenseQueryResult<TData, ListOpportunitiesError | Error>;
        schema: ListOpportunitiesSchema;
        types: {
            parameters: ListOpportunitiesParameters;
            data: ListOpportunitiesData;
            error: ListOpportunitiesError;
        };
    };
    /** @summary Create Opportunity */
    create: {
        /** @summary Create Opportunity */
        getMutationKey(parameters: CreateParameters | void): ServiceOperationMutationKey<CreateSchema, CreateParameters>;
        /**
         * Enables performing asynchronous data mutation operations such as POST, PUT, PATCH, or DELETE requests.
         * Handles loading state, optimistic updates, and error handling.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutation|`useMutation(...)` documentation}
         * @example Mutation with predefined parameters, e.g., for updating
         * ```ts
         * const { mutate, isPending } = qraft.opportunitiesService.create.useMutation({})
         * mutate(body);
         * ```
         * @example Mutation without predefined parameters, e.g., for creating
         * ```ts
         * const { mutate, isPending } = qraft.opportunitiesService.create.useMutation()
         * mutate({
         *     body: bodyPayload
         * });
         * ```
         */
        useMutation<TVariables extends CreateBody, TContext = unknown>(parameters: CreateParameters, options?: ServiceOperationUseMutationOptions<CreateSchema, CreateData, CreateParameters, TVariables, CreateError | Error, TContext>): UseMutationResult<CreateData, CreateError | Error, AreAllOptional<TVariables> extends true ? TVariables | void : TVariables, TContext>;
        /**
         * Enables performing asynchronous data mutation operations such as POST, PUT, PATCH, or DELETE requests.
         * Handles loading state, optimistic updates, and error handling.
         *
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutation|`useMutation(...)` documentation}
         * @example Mutation with predefined parameters, e.g., for updating
         * ```ts
         * const { mutate, isPending } = qraft.opportunitiesService.create.useMutation({})
         * mutate(body);
         * ```
         * @example Mutation without predefined parameters, e.g., for creating
         * ```ts
         * const { mutate, isPending } = qraft.opportunitiesService.create.useMutation()
         * mutate({
         *     body: bodyPayload
         * });
         * ```
         */
        useMutation<TVariables extends MutationVariables<CreateBody, CreateParameters>, TContext = unknown>(parameters: void, options?: ServiceOperationUseMutationOptions<CreateSchema, CreateData, CreateParameters, TVariables, CreateError | Error, TContext>): UseMutationResult<CreateData, CreateError | Error, TVariables, TContext>;
        /**
         * Returns the count of currently in-progress mutations.
         *
         * @summary Create Opportunity
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useIsMutating|`useIsMutating(...)` documentation}
         * @example Check how many mutations are currently in progress for the specified service method.
         * ```ts
         * const createTotal = qraft.opportunitiesService.create.useIsMutating()
         * ```
         * @example Check how many mutations are currently in progress with the specified parameters.
         * ```ts
         * const createTotal = qraft.opportunitiesService.create.useIsMutating({
         *     parameters: {}
         * })
         * ```
         */
        useIsMutating<TContext = unknown>(filters?: MutationFiltersByParameters<CreateBody, CreateData, CreateParameters, CreateError | Error, TContext> | MutationFiltersByMutationKey<CreateSchema, CreateBody, CreateData, CreateParameters, CreateError | Error, TContext>): number;
        /** @summary Create Opportunity */
        isMutating<TContext>(filters?: MutationFiltersByParameters<CreateBody, CreateData, CreateParameters, CreateError | Error, TContext> | MutationFiltersByMutationKey<CreateSchema, CreateBody, CreateData, CreateParameters, CreateError | Error, TContext>): number;
        /** @summary Create Opportunity */
        (options: ServiceOperationMutationFnOptions<CreateBody, CreateParameters>, client?: (schema: CreateSchema, options: ServiceOperationMutationFnOptions<CreateBody, CreateParameters>) => Promise<RequestFnResponse<CreateData, CreateError>>): Promise<RequestFnResponse<CreateData, CreateError>>;
        /**
         * Provides access to the current state of a mutation, including its status, any resulting data, and associated errors.
         *
         * @summary Create Opportunity
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutationState|`useMutationState(...)` documentation}
         * @example Get all variables of all running mutations.
         * ```ts
         * const createPendingMutationVariables = qraft.opportunitiesService.create.useMutationState({
         *     filters: {
         *         status: "pending"
         *     },
         *     select: mutation => mutation.state.variables
         * })
         * ```
         * @example Get all data for specific mutations via the `parameters`.
         * ```ts
         * const createMutationData = qraft.opportunitiesService.create.useMutationState({
         *     filters: {
         *         parameters: {}
         *     },
         *     select: mutation => mutation.state.data
         * })
         * ```
         */
        useMutationState<TContext = unknown, TResult = MutationState<CreateData, CreateError | Error, MutationVariables<CreateBody, CreateParameters>, TContext>>(options?: {
            filters?: MutationFiltersByParameters<CreateBody, CreateData, CreateParameters, CreateError | Error, TContext> | MutationFiltersByMutationKey<CreateSchema, CreateBody, CreateData, CreateParameters, CreateError | Error, TContext>;
            select?: (mutation: Mutation<CreateData, CreateError | Error, MutationVariables<CreateBody, CreateParameters>, TContext>) => TResult;
        }): Array<TResult>;
        schema: CreateSchema;
        types: {
            parameters: CreateParameters;
            data: CreateData;
            error: CreateError;
            body: CreateBody;
        };
    };
}
export const opportunitiesService: {
    /** @summary Get Opportunities */
    listOpportunities: {
        schema: {
            method: "get";
            url: "/opportunities";
        };
    };
    /** @summary Create Opportunity */
    create: {
        schema: {
            method: "post";
            url: "/opportunities";
            mediaType: [
                "application/json"
            ];
        };
    };
} = {
    listOpportunities: {
        schema: {
            method: "get",
            url: "/opportunities"
        }
    },
    create: {
        schema: {
            method: "post",
            url: "/opportunities",
            mediaType: ["application/json"]
        }
    }
};
type ListOpportunitiesSchema = {
    method: "get";
    url: "/opportunities";
};
type ListOpportunitiesParameters = undefined;
type ListOpportunitiesData = paths["/opportunities"]["get"]["responses"]["200"]["content"]["application/json"];
type ListOpportunitiesError = unknown;
type CreateSchema = {
    method: "post";
    url: "/opportunities";
    mediaType: [
        "application/json"
    ];
};
type CreateParameters = {};
type CreateData = paths["/opportunities"]["post"]["responses"]["201"]["content"]["application/json"];
type CreateError = paths["/opportunities"]["post"]["responses"]["422"]["content"]["application/json"];
type CreateBody = NonNullable<paths["/opportunities"]["post"]["requestBody"]>["content"]["application/json"];
