/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import type { paths } from "../schema";
import type { ServiceOperationQuery, ServiceOperationMutation } from "@openapi-qraft/react";
export interface OpportunitiesService {
    /** @summary Get Opportunities */
    listOpportunities: ServiceOperationQuery<{
        method: "get";
        url: "/opportunities";
    }, paths["/opportunities"]["get"]["responses"]["200"]["content"]["application/json"], undefined, unknown>;
    /** @summary Create Opportunity */
    createOpprtunity: ServiceOperationMutation<{
        method: "post";
        url: "/opportunities";
        mediaType: "application/json";
    }, NonNullable<paths["/opportunities"]["post"]["requestBody"]>["content"]["application/json"], paths["/opportunities"]["post"]["responses"]["201"]["content"]["application/json"], undefined, paths["/opportunities"]["post"]["responses"]["422"]["content"]["application/json"]>;
    /** @summary Seed Opportunities */
    seedOpportunities: ServiceOperationMutation<{
        method: "post";
        url: "/opportunities/seed";
    }, undefined, paths["/opportunities/seed"]["post"]["responses"]["201"]["content"]["application/json"], undefined, unknown>;
}
export const opportunitiesService: {
    /** @summary Get Opportunities */
    listOpportunities: {
        schema: {
            method: "get";
            url: "/opportunities";
        };
    };
    /** @summary Create Opportunity */
    createOpprtunity: {
        schema: {
            method: "post";
            url: "/opportunities";
            mediaType: "application/json";
        };
    };
    /** @summary Seed Opportunities */
    seedOpportunities: {
        schema: {
            method: "post";
            url: "/opportunities/seed";
        };
    };
} = {
    listOpportunities: {
        schema: {
            method: "get",
            url: "/opportunities"
        }
    },
    createOpprtunity: {
        schema: {
            method: "post",
            url: "/opportunities",
            mediaType: "application/json"
        }
    },
    seedOpportunities: {
        schema: {
            method: "post",
            url: "/opportunities/seed"
        }
    }
};
