/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import type { paths } from "../schema";
import type { ServiceOperationMutation } from "@openapi-qraft/react";
export interface SeedService {
    /** @summary Seed Dummy Data */
    seedDummyDataSeedDummyPost: ServiceOperationMutation<{
        method: "post";
        url: "/seed/dummy";
    }, undefined, paths["/seed/dummy"]["post"]["responses"]["200"]["content"]["application/json"], undefined, unknown>;
}
export const seedService: {
    /** @summary Seed Dummy Data */
    seedDummyDataSeedDummyPost: {
        schema: {
            method: "post";
            url: "/seed/dummy";
        };
    };
} = {
    seedDummyDataSeedDummyPost: {
        schema: {
            method: "post",
            url: "/seed/dummy"
        }
    }
};
