/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import type { paths } from "../schema";
import type { ServiceOperationMutation } from "@openapi-qraft/react";
export interface UsersService {
    /** @summary Make User */
    createUser: ServiceOperationMutation<{
        method: "post";
        url: "/users/";
        mediaType: "application/json";
    }, NonNullable<paths["/users/"]["post"]["requestBody"]>["content"]["application/json"], paths["/users/"]["post"]["responses"]["201"]["content"]["application/json"], undefined, paths["/users/"]["post"]["responses"]["422"]["content"]["application/json"]>;
}
export const usersService: {
    /** @summary Make User */
    createUser: {
        schema: {
            method: "post";
            url: "/users/";
            mediaType: "application/json";
        };
    };
} = {
    createUser: {
        schema: {
            method: "post",
            url: "/users/",
            mediaType: "application/json"
        }
    }
};
