
name: Lint
on:
  push: {}

jobs:
  ruff:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: backend/send_me

    name: Ruff Checks
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: x64
      - run: pip install poetry==2.0.1
      - run: poetry install --with lint,types
      - run: poetry run ruff check send_me

  pyright:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: backend/send_me

    name: Pyright Checks
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: x64
      - run: pip install poetry==2.0.1
      - run: poetry install --with lint,types
      - run: poetry run pyright send_me/

  biome:
    runs-on: ubuntu-22.04
    name: Biome
    steps:
      - uses: actions/checkout@v4
      - name: NPM Install
        run: npm ci
      - name: NPM Run Biome
        run: npm run biome

  tsc:
    runs-on: ubuntu-22.04
    name: Typescript

    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - name: NPM Install
        run: npm ci
      - name: NPM Run typecheck
        run: npm run typecheck

